couchdb_peer1_org2:
    container_name: ${CONTAINERCOUCHDB}
    image: hyperledger/fabric-couchdb:0.4.18
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=secret
    ports:
      - ${ASSIGN_PORT}:5984
   

peer1.org2.com:
    container_name: ${CONTAINERNAME}
    image: "hyperledger/fabric-peer:2.1"
    environment:
      - FABRIC_CA_CLIENT_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - FABRIC_CA_CLIENT_TLS_CERTFILES=/data/crypto-config/peerOrganizations/${ORGG}.com/ca/ca.${ORGG}.com-cert.pem
      - ENROLLMENT_URL=https://admin:adminpw@${ORDERERORGHOSTIP}:7056
      - PEER_NAME=${PEER}.${ORGG}.com
      - PEER_HOME=/opt/gopath/src/github.com/hyperledger/fabric/peer
      - PEER_HOST=${HOSTIP}
      - PEER_NAME_PASS=${PEER}.${ORGG}.com:${PEER}.${ORGG}.compw
      - ORG=${ORGG}
      - PEER=${PEER}
      - DOMAIN=${ORGG}.com
      - CORE_PEER_ID=${PEER}.${ORGG}.com
      - CORE_PEER_ADDRESS=0.0.0.0:7054
      - CORE_PEER_LOCALMSPID=${ORGG}MSP
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/msp
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/data/crypto-config/peerOrganizations/${ORGG}.com/ca/ca.${ORGG}.com-cert.pem
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${EXTERNALENDPOINT}
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_GOSSIP_BOOTSTRAP=${BOOTSTRAP}
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=user
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=secret
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=${HOSTIP}:${ASSIGN_PORT}
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/sh -c '/scripts/start-peer.sh 2>&1 | tee /data/logs/${PEER}.${ORGG}.com.log;'
    volumes:
      - /opt/hyper/docker-compose/peer/script:/scripts
      - /opt/hyper/data:/data
      - /var/run:/host/var/run
    ports:
      - ${USEPORT}:7051
      
